# Generated by Django 3.2.6 on 2021-08-21 08:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bakery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=5)),
                ('billNumber', models.CharField(max_length=10, unique=True)),
                ('created_datetime', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
